# Where things are
source:       .
destination:  ./_site
plugins_dir:  _plugins
layouts_dir:  _layouts
data_dir:     _data
includes_dir: resources

# Handling Reading
safe:         false
include:      [".htaccess"]
exclude:      ["node_modules", "vendor/bundle/", "vendor/cache/", "vendor/gems/", "vendor/ruby/"]
keep_files:   [".git", ".svn"]
encoding:     "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

excerpt_separator: <!--more-->

# Filtering Content
show_drafts: null
limit_posts: 0
future:      false
unpublished: false

# Plugins
plugins:
  - "jekyll/scholar"

# Publications
scholar:
  bibliography_template: bib
  style: _bibliography/customstyle
  repository: files
  group_order: descending
  bibliography_group_tag: b
  bibliography_list_tag: ul
  
# Conversion
markdown:    kramdown
incremental: false
highlighter: rouge

# Serving
detach:  false
port:    4000
host:    127.0.0.1
#baseurl: "/storm"
show_dir_listing: false

# Outputting
permalink:     date
paginate_path: /page:num
timezone:      UTC

future:   true
quiet:    false
verbose:  true
defaults: []

# Content
category-list: [Obtain Storm, Background, Use Storm, Develop with Storm]

liquid:
  error_mode: warn

# Markdown Processors

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  input:          GFM
  hard_wrap:      false
  footnote_nr:    1
  syntax_highlighter: rouge
